### ISSUE TITLE
Interesting field: `"biblionote": {"type": "remark", "content": "."}`

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-3gpp#3]
Example item: https://demo.bibxml.org/api/v1/ref/3gpp/TR_33.879_REL-13_0.1.0/

Not sure it’s as designed.

**Comment by strogonoff** [comment]
The field seems to exist in the grammar, but content seems suspect.

**Comment by ronaldtse** [comment]
@strogonoff original data.

In the status table:
<img width="1606" alt="Screenshot 2021-12-17 at 10 25 20 AM" src="https://user-images.githubusercontent.com/11865/146478711-d3a7d09c-2915-4d41-a705-330085a866ff.png">
 
The `comment` field seems to be empty. This is the "spec version remark".

In the spec-release table:
<img width="707" alt="Screenshot 2021-12-17 at 10 26 32 AM" src="https://user-images.githubusercontent.com/11865/146478837-cff11932-e6f1-4851-baae-755d6af40f7e.png">

Here's where the `.` comes from. This is the "spec release" remark.

@andrew2net we seem to be missing the "spec version remark" from the status table?

**Comment by andrew2net** [comment]
@ronaldtse if the comment from the status table is not nil it will be represented as `biblionote": {"type": "comment", "content": "Some comment"}`. The document "3GPP TR 33.879:Rel-13/0.1.0" has comment `nil` in status table and remarks `.` in the spec-release table.
Obviously comments with "." should be removed, shouldn't they?

**Comment by ronaldtse** [comment]
@andrew2net true, let's remove the `comment` being `.`. This is considered data cleaning and is acceptable.
