### ISSUE TITLE
Encountered new docid type “rapporteurId”

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-3gpp#4]
Is this an actual document type, like DOI or IEEE?

**Comment by ronaldtse** [comment]
No. This is wrong. `rapporteurId` is not a Document Identifier, it is the 3GPP internal ID of the "Rapporteur" of the document (a person).

Ping @andrew2net .

**Comment by andrew2net** [comment]
fixed in https://github.com/relaton/relaton-3gpp/issues/5
