### ISSUE TITLE
Unknown field “abstract” (should be “docabstract”?)

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-3gpp#6]
Item: https://demo.bibxml.org/api/v1/ref/3gpp/TS_27.007_REL-15_15.3.0/

**Comment by ronaldtse** [comment]
`abstract` seems correct:
* https://github.com/relaton/relaton-models/blob/87b319a8872db45e8f2343a5f7ad4f806de041a9/models/BibliographicItem.lutaml#L82
* https://github.com/relaton/relaton-models/blob/87b319a8872db45e8f2343a5f7ad4f806de041a9/grammars/biblio.rnc#L367

**Comment by strogonoff** [comment]
@ronaldtse I don’t see `abstract` there. if I comply with the spec, which apparently uses `bibabstract` (I made a typo in the title), it won’t work because the data is using `abstract`.

If the above grammar is not supposed to specify the exact field names, then fine, but then I’ll bring up again the question on where to find the the exact spec that can be relied upon for that.

**Comment by ronaldtse** [comment]
Ping @opoudjis @andrew2net for the proper field name here.

**Comment by andrew2net** [comment]
Abstract should be an `Array` of `Hash` or `RelatonBib::FormattedString` (`Array<Hash, RelatonBib::FormattedString>`).
If element of array is a `Hash` then `RelatonBib::FormattedString` will be created in `RelatonBib::BibliographicItem#inilialize`.
Structure of `Hash` should be `{ content: String, language: String, script: String, format: String }`
@strogonoff where does the message `Unknown field “abstract”` come from? Could you provide a full log?

**Comment by strogonoff** [comment]
It’s not a message, just from what I saw. Relaton grammar has field `bibabstract` but not `abstract`.

**Comment by andrew2net** [comment]
@strogonoff in the grammar `bibabstract` is a name of definition `bibabstract = element abstract { FormattedString }`but it describes an `abstract` XML element.
I agree, we have inconsistency in fields names. It happened because the project has grown significantly and we didn't have a strong specification. Unfortunately, it isn't so easy to fix all these inconsistencies.

**Comment by strogonoff** [comment]
BibXML service now uses field named `abstract`.
