### ISSUE TITLE
Deficiency in this source compared to IETF xml2rfc

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-3gpp#7]
IETF’s xml2rfc apparently has publication dates:

http://xml2rfc.tools.ietf.org/public/rfc/bibxml5/reference.3GPP.01.31.xml

We apparently don’t, from checking these items: https://dev.bibxml.org/search/?query=3GPP+01.31&allow_format_fallback=True&bypass_cache=True

Also, IETF’s source specifies 3GPP org as an author, while we only specify the person.

**Comment by ronaldtse** [comment]
@strogonoff can you please file this issue also under relaton-3gpp? @andrew2net needs to be informed about this.

**Comment by ronaldtse** [comment]
@strogonoff specifically is asking for:
1. Map the 3GPP "confirmed" date to BibXML as published date. 3GPP does not have a notion of "published date", only "upload date" provided by the 3GPP database. This is to be done by the Relaton => BibXML mapping.

In the Relaton JSON from that endpoint you provided:
```json
        "person": {
          "name": {
            "completename": {
              "content": "SAHLIN, Bengt",
              "format": null,
              "script": [
                "Latn"
              ],
              "language": [
                "en"
              ]
            },
            "surname": null,
            "initial": null,
            "forename": null
          },
          "affiliation": [
            {
              "organization": {
                "name": [
                  "Ericsson LM"
                ],
                "contact": null,
                "url": null,
                "abbreviation": null
              }
            }
          ]
        },
        "organization": null
```

This is to be done in the relaton-bib-py package (ping @CAMOBAP ):
* The authorship information is complete -- the name is `"SAHLIN, Bengt"` and the organization is `"Ericsson LM"`. We Relaton-Py needs to expose that to BibXML.
* When serialising to BibXML, we only use the name "3GPP" without the full name, and not setting the abbreviation (similar to the situation with W3C).

This is to be done in the relaton-3gpp gem (ping @andrew2net ):
* The "organization" author for 3GPP documents is 3GPP. The organization name should be "3rd Generation Partnership Project" and the abbreviation is "3GPP".
* When serialising to BibXML, we only use the name "3GPP" without the full name, and not setting the abbreviation (similar to the situation with W3C).

**Comment by CAMOBAP** [comment]
@ronaldtse I will check how `relaton-bib-py` works with 3GPP documents

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by strogonoff** [comment]
> Map the 3GPP "confirmed" date to BibXML as published date. 3GPP does not have a notion of "published date", only "upload date" provided by the 3GPP database.

There seems to be a misunderstanding which we need to agree on before @CAMOBAP does anything.

It looks like authoritative source for 3gpp calls what we consider “published date” something else. My position is that “our Relaton datasets should adapt authoritative source data if needed and provide a published date according to Relaton spec”. But Ronald seems to be saying “our Relaton parsers (relaton-bib-py, etc.) should interpret confirmed date as published date in case of 3gpp”.

I don’t agree with Ronald on this: our libraries should not need to parse Relaton data differently depending on where they come from.

---

For the other XML parsing issues, I think acting on them right now may be unnecessary. BibXML service isn’t using relaton-bib-py for now, it’s using its own `to_xml` implementation. Also, BibXML service is a great way to tell what kind of XML does IETF expect (we will hear complaints if something is off). Therefore, we can see first which issues come up with my implementation of `to_xml`, and later migrate relaton-bib-py to that implementation. But this is probably another ticket anyway.

**Comment by ronaldtse** [comment]
> our libraries should not need to parse Relaton data differently depending on where they come from.

The issue is a bit more nuanced than it was described. Let me explain. 

1. Different organizations have different semantics in their metadata. Most organizations do not share a single bibliographic model. 
2. Every format is backed by a data model. Relaton JSON/YAML/XML’s “generic” model is one, BibXML is one, and 3GPP’s is also another. 
3. Our work here is to bridge these models in order to serialize one to another. Typically, if we have the authority (eg we are officially delegated by authority, or that we work with the authority) we can of finally create a semantic mapping between attributes. 
4. In this case, we do not have the authority from 3GPP to declare that a 3GPP “confirmation date” is equal to a Relaton publication date. However, we do know that BibXML considers the “3GPP confirmation date” is considered the “BibXML publication date”. 

In such a model mapping exercise, we have to respect and understand the difference in semantics. Hope this clears it up.

**Comment by strogonoff** [comment]
@ronaldtse thanks for in-depth summary. My takeaways:

- We should not add “published” dates in our Relaton data 3gpp source
  - However, I can see that there is no “uploaded” date either, and that could probably be addressed?
- I don’t think we should alter the way BibliographicItem is parsed for 3gpp
- I agree that we could do this:

  > BibXML service’s to_xml() handling should fall back to date of another type (if there is no date of “published” type) when formatting <date> of a <reference>.

  So if 3GPP bibliographic item has an “uploaded” type date, and to_xml detects no “published” date, it will fall back to “uploaded”. (There can be a list of acceptable substitutes for published dates, possibly dependent on document identifier type.)

**Comment by ronaldtse** [comment]
@strogonoff actually there is an error in what I said about "confirmation date". The "confirmation date" is not the "publication date", it is the date that the standard was "confirmed" that it does not need updating, after "publication".

Let's compare these two sources:
* http://xml2rfc.tools.ietf.org/public/rfc/bibxml5/reference.3GPP.01.31.xml
* https://github.com/ietf-ribose/relaton-data-3gpp/blob/main/data/TR_01.31_R98_7.0.1.yaml

First source:
```xml
<reference anchor="3GPP.01.31">
<front>
<title>
Fraud Information Gathering System (FIGS); Service requirements; Stage 0
</title>
<author>
<organization>3GPP</organization>
</author>
<date day="26" month="June" year="1998"/>
</front>
<seriesInfo name="3GPP TR" value="01.31 7.0.1"/>
<format type="HTML" target="http://www.3gpp.org/ftp/Specs/html-info/0131.htm"/>
</reference>
```

In the new data (latter source), the only date provided is the "confirmation date":
https://github.com/ietf-ribose/relaton-data-3gpp/blob/9ff6ccb22ae83ed71705dadebe770cecbb121413/data/TR_01.31_R98_7.0.1.yaml#L18-L19

However, the source data provides these dates too:
<img width="1141" alt="Screenshot 2022-02-19 at 1 25 41 AM" src="https://user-images.githubusercontent.com/11865/154732298-7a81a38b-d19e-4218-b72e-e5de64e0dafe.png">
<img width="1140" alt="Screenshot 2022-02-19 at 1 25 52 AM" src="https://user-images.githubusercontent.com/11865/154732314-b9f81fbb-ea77-472f-920b-1d2585599ff8.png">

Here the "ACHIEVED DATE" is clearly the "publication date". 

@andrew2net needs to fix this.

**Comment by strogonoff** [comment]
@ronaldtse BibXML service’s to_xml() currently already [treats](https://github.com/ietf-ribose/bibxml-service/blob/0fcc9d7b09d1f54872b7d623ac3300f1ed645c6a/xml2rfc_compat/serializer.py#L114-L144) the first available date as xml2rfc “published” date (if Relaton data contains no actual published date), so I don’t know if this ticket is still an issue for me at least.

**Comment by ronaldtse** [comment]
Thanks @strogonoff , in any case, the Relaton 3GPP issue has been fixed by @andrew2net too.

**Comment by strogonoff** [comment]
Yes, closing!
